In [1]:
import numpy as np

In [4]:
n1 = np.array ([1,2,3,4])
print(n1)
print(type(n1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [5]:
x =[]
len(dir(n1))

166

In [6]:
n1.shape

(4,)

In [9]:
n2 = np.array([[1,2,3], [2,3,5]])
print(n2)
print(n2.shape)

[[1 2 3]
 [2 3 5]]
(2, 3)


creating matrix
- arange
- linspace
- random.rand
- random.randn
- random.randint
- eye
- ones
- zeroes


In [11]:
x = np.arange(-10, 10, .2)
x.shape

(100,)

In [12]:
y = np.linspace(1,5,25)
print(y)

[1.         1.16666667 1.33333333 1.5        1.66666667 1.83333333
 2.         2.16666667 2.33333333 2.5        2.66666667 2.83333333
 3.         3.16666667 3.33333333 3.5        3.66666667 3.83333333
 4.         4.16666667 4.33333333 4.5        4.66666667 4.83333333
 5.        ]


In [13]:
np.random.rand(3,3)

array([[0.84488459, 0.71541304, 0.20486667],
       [0.39591814, 0.44363253, 0.20930192],
       [0.19709216, 0.0295866 , 0.07428241]])

In [17]:
np.random.randn(10)

array([ 0.72299824,  0.42107148, -0.37639093, -0.3881783 , -0.31648034,
       -1.01496957,  0.67068201, -0.64250695, -1.74181052, -1.36709913])

In [16]:
np.random.randint(1,5 ,(5,5))

array([[3, 3, 1, 1, 2],
       [2, 4, 4, 3, 1],
       [4, 1, 2, 3, 3],
       [2, 3, 3, 1, 3],
       [4, 3, 3, 3, 4]])

In [18]:
x = np.random.randint(1,10,(3,2))
y = np.random.randint(1,10,(3,2))
print(x)
print(y)


[[8 3]
 [2 5]
 [5 3]]
[[2 8]
 [3 6]
 [4 6]]


In [19]:
x + 5

array([[13,  8],
       [ 7, 10],
       [10,  8]])

In [20]:
x+y

array([[10, 11],
       [ 5, 11],
       [ 9,  9]])

In [21]:
x *y

array([[16, 24],
       [ 6, 30],
       [20, 18]])

In [22]:
x.T # transpose

array([[8, 2, 5],
       [3, 5, 3]])

In [ ]:
x.dot(y.t)

In [23]:
np.sin(x)

array([[ 0.98935825,  0.14112001],
       [ 0.90929743, -0.95892427],
       [-0.95892427,  0.14112001]])

In [24]:
print(x.sum())
print(x.mean())
print(x.std())

26
4.333333333333333
1.9720265943665387
