In [17]:
import numpy as np

In [18]:
n1 = np.array ([1,2,3,4])
print(n1)
print(type(n1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [19]:
x =[]
len(dir(n1))

166

In [20]:
n1.shape

(4,)

In [21]:
n2 = np.array([[1,2,3], [2,3,5]])
print(n2)
print(n2.shape)

[[1 2 3]
 [2 3 5]]
(2, 3)


creating matrix
- arange
- linspace
- random.rand
- random.randn
- random.randint
- eye
- ones
- zeroes


In [22]:
x = np.arange(-10, 10, .2)
x.shape

(100,)

In [23]:
y = np.linspace(1,5,25)
print(y)

[1.         1.16666667 1.33333333 1.5        1.66666667 1.83333333
 2.         2.16666667 2.33333333 2.5        2.66666667 2.83333333
 3.         3.16666667 3.33333333 3.5        3.66666667 3.83333333
 4.         4.16666667 4.33333333 4.5        4.66666667 4.83333333
 5.        ]


In [24]:
np.random.rand(3,3)

array([[0.75694107, 0.34829413, 0.60467848],
       [0.48703777, 0.52082934, 0.46599734],
       [0.03852876, 0.4480922 , 0.56647027]])

In [25]:
np.random.randn(10)

array([ 0.83655812,  0.06530265, -0.64486656, -0.14870082,  1.6601303 ,
       -0.14993141, -0.17992811, -0.0550168 , -1.12354926,  0.65648225])

In [26]:
np.random.randint(1,5 ,(5,5))

array([[4, 4, 4, 1, 1],
       [1, 1, 4, 3, 1],
       [1, 2, 4, 2, 3],
       [1, 3, 2, 2, 4],
       [3, 1, 1, 3, 2]])

In [27]:
x = np.random.randint(1,10,(3,2))
y = np.random.randint(1,10,(3,2))
print(x)
print(y)


[[3 2]
 [2 2]
 [7 4]]
[[8 1]
 [7 3]
 [1 8]]


In [28]:
x + 5

array([[ 8,  7],
       [ 7,  7],
       [12,  9]])

In [29]:
x+y

array([[11,  3],
       [ 9,  5],
       [ 8, 12]])

In [30]:
x *y

array([[24,  2],
       [14,  6],
       [ 7, 32]])

In [31]:
x.T # transpose

array([[3, 2, 7],
       [2, 2, 4]])

In [32]:
x.dot(y.T)

array([[26, 27, 19],
       [18, 20, 18],
       [60, 61, 39]])

In [33]:
np.sin(x)

array([[ 0.14112001,  0.90929743],
       [ 0.90929743,  0.90929743],
       [ 0.6569866 , -0.7568025 ]])

In [34]:
print(x.sum())
print(x.mean())
print(x.std())

20
3.3333333333333335
1.7950549357115013


In [35]:
a = np.linspace(0,5,50)
print(a.shape)
a2 = a.reshape(10,5)
print(a2)
print(a2.shape)


(50,)
[[0.         0.10204082 0.20408163 0.30612245 0.40816327]
 [0.51020408 0.6122449  0.71428571 0.81632653 0.91836735]
 [1.02040816 1.12244898 1.2244898  1.32653061 1.42857143]
 [1.53061224 1.63265306 1.73469388 1.83673469 1.93877551]
 [2.04081633 2.14285714 2.24489796 2.34693878 2.44897959]
 [2.55102041 2.65306122 2.75510204 2.85714286 2.95918367]
 [3.06122449 3.16326531 3.26530612 3.36734694 3.46938776]
 [3.57142857 3.67346939 3.7755102  3.87755102 3.97959184]
 [4.08163265 4.18367347 4.28571429 4.3877551  4.48979592]
 [4.59183673 4.69387755 4.79591837 4.89795918 5.        ]]
(10, 5)


In [36]:
a2.reshape(5,5,2)

array([[[0.        , 0.10204082],
        [0.20408163, 0.30612245],
        [0.40816327, 0.51020408],
        [0.6122449 , 0.71428571],
        [0.81632653, 0.91836735]],

       [[1.02040816, 1.12244898],
        [1.2244898 , 1.32653061],
        [1.42857143, 1.53061224],
        [1.63265306, 1.73469388],
        [1.83673469, 1.93877551]],

       [[2.04081633, 2.14285714],
        [2.24489796, 2.34693878],
        [2.44897959, 2.55102041],
        [2.65306122, 2.75510204],
        [2.85714286, 2.95918367]],

       [[3.06122449, 3.16326531],
        [3.26530612, 3.36734694],
        [3.46938776, 3.57142857],
        [3.67346939, 3.7755102 ],
        [3.87755102, 3.97959184]],

       [[4.08163265, 4.18367347],
        [4.28571429, 4.3877551 ],
        [4.48979592, 4.59183673],
        [4.69387755, 4.79591837],
        [4.89795918, 5.        ]]])

In [38]:
m = np.random.randint(1,10,(10,10))
print(m)

[[5 9 9 6 4 7 4 6 2 1]
 [4 1 2 4 6 5 8 6 3 5]
 [7 5 3 4 7 7 9 9 3 3]
 [8 2 6 8 3 2 2 8 2 5]
 [9 9 8 7 7 7 1 6 7 1]
 [4 8 7 3 9 6 4 8 5 6]
 [9 5 7 4 7 7 7 4 1 7]
 [6 7 8 6 7 4 2 3 1 9]
 [8 8 4 1 2 4 7 9 6 6]
 [1 3 1 6 3 9 8 3 2 7]]


In [39]:
print(m[0,0]) # first row first column

5


In [40]:
print(m[0]) #first row
print(m[1]) # fisrt 3 rows
print(m[-1]) # last row
print(m[:3]) # fisrt 3 rows
print(m[-3:]) # last 3 rows

[5 9 9 6 4 7 4 6 2 1]
[4 1 2 4 6 5 8 6 3 5]
[1 3 1 6 3 9 8 3 2 7]
[[5 9 9 6 4 7 4 6 2 1]
 [4 1 2 4 6 5 8 6 3 5]
 [7 5 3 4 7 7 9 9 3 3]]
[[6 7 8 6 7 4 2 3 1 9]
 [8 8 4 1 2 4 7 9 6 6]
 [1 3 1 6 3 9 8 3 2 7]]


In [41]:
print(m[:,0]) # first column
print(m[:,-1])# last column
print(m[:,:3]) # first 3 column
print(m[:,-3:]) # last 3 column

[5 4 7 8 9 4 9 6 8 1]
[1 5 3 5 1 6 7 9 6 7]
[[5 9 9]
 [4 1 2]
 [7 5 3]
 [8 2 6]
 [9 9 8]
 [4 8 7]
 [9 5 7]
 [6 7 8]
 [8 8 4]
 [1 3 1]]
[[6 2 1]
 [6 3 5]
 [9 3 3]
 [8 2 5]
 [6 7 1]
 [8 5 6]
 [4 1 7]
 [3 1 9]
 [9 6 6]
 [3 2 7]]


In [42]:
print(m[:,[0,2,3,5]])

[[5 9 6 7]
 [4 2 4 5]
 [7 3 4 7]
 [8 6 8 2]
 [9 8 7 7]
 [4 7 3 6]
 [9 7 4 7]
 [6 8 6 4]
 [8 4 1 4]
 [1 1 6 9]]


- filtering

In [43]:
m 

array([[5, 9, 9, 6, 4, 7, 4, 6, 2, 1],
       [4, 1, 2, 4, 6, 5, 8, 6, 3, 5],
       [7, 5, 3, 4, 7, 7, 9, 9, 3, 3],
       [8, 2, 6, 8, 3, 2, 2, 8, 2, 5],
       [9, 9, 8, 7, 7, 7, 1, 6, 7, 1],
       [4, 8, 7, 3, 9, 6, 4, 8, 5, 6],
       [9, 5, 7, 4, 7, 7, 7, 4, 1, 7],
       [6, 7, 8, 6, 7, 4, 2, 3, 1, 9],
       [8, 8, 4, 1, 2, 4, 7, 9, 6, 6],
       [1, 3, 1, 6, 3, 9, 8, 3, 2, 7]])

In [44]:
m <5 # boolean filter

array([[False, False, False, False,  True, False,  True, False,  True,
         True],
       [ True,  True,  True,  True, False, False, False, False,  True,
        False],
       [False, False,  True,  True, False, False, False, False,  True,
         True],
       [False,  True, False, False,  True,  True,  True, False,  True,
        False],
       [False, False, False, False, False, False,  True, False, False,
         True],
       [ True, False, False,  True, False, False,  True, False, False,
        False],
       [False, False, False,  True, False, False, False,  True,  True,
        False],
       [False, False, False, False, False,  True,  True,  True,  True,
        False],
       [False, False,  True,  True,  True,  True, False, False, False,
        False],
       [ True,  True,  True, False,  True, False, False,  True,  True,
        False]])

In [45]:
m [m <5] 

array([4, 4, 2, 1, 4, 1, 2, 4, 3, 3, 4, 3, 3, 2, 3, 2, 2, 2, 1, 1, 4, 3,
       4, 4, 4, 1, 4, 2, 3, 1, 4, 1, 2, 4, 1, 3, 1, 3, 3, 2])

In [46]:
m[ m>3]

array([5, 9, 9, 6, 4, 7, 4, 6, 4, 4, 6, 5, 8, 6, 5, 7, 5, 4, 7, 7, 9, 9,
       8, 6, 8, 8, 5, 9, 9, 8, 7, 7, 7, 6, 7, 4, 8, 7, 9, 6, 4, 8, 5, 6,
       9, 5, 7, 4, 7, 7, 7, 4, 7, 6, 7, 8, 6, 7, 4, 9, 8, 8, 4, 4, 7, 9,
       6, 6, 6, 9, 8, 7])

In [47]:
m[(m>=3) & (m<=6)]

array([5, 6, 4, 4, 6, 4, 4, 6, 5, 6, 3, 5, 5, 3, 4, 3, 3, 6, 3, 5, 6, 4,
       3, 6, 4, 5, 6, 5, 4, 4, 6, 6, 4, 3, 4, 4, 6, 6, 3, 6, 3, 3])